name: その他・要望
description: バグ報告以外の要望や質問はこちらからどうぞ
title: "[ETC]: "
labels: ["etc"]
body:
  - type: textarea
    attributes:
      label: 要望内容
      description: 伝えたいことを書いてください
      placeholder: 例：○○の機能を追加して欲しいです
    validations:
      required: true
